=== Kevin-Cravioto/ordinario-ftw/xml/biblioteca.dtd
<!ELEMENT biblioteca (album+)>
<!ELEMENT album (titulo, artista, genero, anio, portada, calificacion, canciones)>
<!ATTLIST album id CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT portada (#PCDATA)>
<!ELEMENT calificacion (#PCDATA)>
<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion (nombre, duracion, calificacion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>

=== Kevin-Cravioto/ordinario-ftw/xml/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    
    <album id="1">
        <titulo>Appetite for Destruction</titulo>
        <artista>Guns N' Roses</artista>
        <genero>Rock</genero>
        <anio>1987</anio>
        <portada>../img/appetite.jpg</portada>
        <calificacion>5</calificacion>
        <canciones>
            <cancion>
                <nombre>Welcome to the Jungle</nombre>
                <duracion>4:31</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>It's So Easy</nombre>
                <duracion>3:22</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Nightrain</nombre>
                <duracion>4:28</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>Out ta Get Me</nombre>
                <duracion>4:24</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Mr. Brownstone</nombre>
                <duracion>3:49</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Paradise City</nombre>
                <duracion>6:46</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>My Michelle</nombre>
                <duracion>3:40</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Think About You</nombre>
                <duracion>3:52</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Sweet Child O' Mine</nombre>
                <duracion>5:56</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>You're Crazy</nombre>
                <duracion>3:17</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Anything Goes</nombre>
                <duracion>3:26</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Rocket Queen</nombre>
                <duracion>6:13</duracion>
                <calificacion>5</calificacion>
            </cancion>
        </canciones>
    </album>

    <album id="2">
        <titulo>Nevermind</titulo>
        <artista>Nirvana</artista>
        <genero>Grunge</genero>
        <anio>1991</anio>
        <portada>../img/nevermind.jpg</portada>
        <calificacion>4</calificacion>
        <canciones>
            <cancion>
                <nombre>Smells Like Teen Spirit</nombre>
                <duracion>5:01</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>In Bloom</nombre>
                <duracion>4:15</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>Come As You Are</nombre>
                <duracion>3:39</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>Breed</nombre>
                <duracion>3:04</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Lithium</nombre>
                <duracion>4:17</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>Polly</nombre>
                <duracion>2:57</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Territorial Pissings</nombre>
                <duracion>2:23</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Drain You</nombre>
                <duracion>3:44</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>Lounge Act</nombre>
                <duracion>2:37</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Stay Away</nombre>
                <duracion>3:33</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>On a Plain</nombre>
                <duracion>3:16</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>Something in the Way</nombre>
                <duracion>3:52</duracion>
                <calificacion>4</calificacion>
            </cancion>
        </canciones>
    </album>

    <album id="3">
        <titulo>DINASTÍA</titulo>
        <artista>Peso Pluma &amp; Tito Double P</artista>
        <genero>Música Mexicana</genero>
        <anio>2025</anio>
        <portada>../img/dinastia.jpg</portada>
        <calificacion>5</calificacion>
        <canciones>
            <cancion>
                <nombre>intro</nombre>
                <duracion>1:50</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>dopamina</nombre>
                <duracion>3:12</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>ni pedo</nombre>
                <duracion>2:45</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>putielegante</nombre>
                <duracion>3:05</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>7-3</nombre>
                <duracion>2:58</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>billete</nombre>
                <duracion>3:15</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>daño</nombre>
                <duracion>2:50</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>trucha</nombre>
                <duracion>3:22</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>morras II</nombre>
                <duracion>3:10</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>mezcal</nombre>
                <duracion>2:48</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>malibu</nombre>
                <duracion>3:01</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>20s</nombre>
                <duracion>2:35</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>viejo lobo</nombre>
                <duracion>3:18</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>tu con el</nombre>
                <duracion>2:55</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>bckpckbyz</nombre>
                <duracion>3:43</duracion>
                <calificacion>5</calificacion>
            </cancion>
        </canciones>
    </album>

    <album id="4">
        <titulo>ASTROWORLD</titulo>
        <artista>Travis Scott</artista>
        <genero>Hip-Hop</genero>
        <anio>2018</anio>
        <portada>../img/astroworld.jpg</portada>
        <calificacion>5</calificacion>
        <canciones>
            <cancion>
                <nombre>STARGAZING</nombre>
                <duracion>4:31</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>CAROUSEL</nombre>
                <duracion>3:00</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>SICKO MODE</nombre>
                <duracion>5:12</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>R.I.P. SCREW</nombre>
                <duracion>3:05</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>STOP TRYING TO BE GOD</nombre>
                <duracion>5:38</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>NO BYSTANDERS</nombre>
                <duracion>3:38</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>SKELETONS</nombre>
                <duracion>2:25</duracion>
                <calificacion>5</calificacion>
            </cancion>
            <cancion>
                <nombre>WAKE UP</nombre>
                <duracion>3:52</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>5% TINT</nombre>
                <duracion>3:16</duracion>
                <calificacion>4</calificacion>
            </cancion>
            <cancion>
                <nombre>NC-17</nombre>
                <duracion>2:37</duracion>
                <calificacion>4</calificacion>
